### PR TITLE
deps: update hyper 0.14.2 -> 0.14.4

### PR DESCRIPTION
**Pull request by daviddrysdale**
Move past RUSTSEC-2021-0020

### CODE REVIEW

**Review by conradgrobler — COMMENTED** [review]
Does tonic work with this version of hyper?

**Review by conradgrobler — APPROVED** [review]
Seeing that it builds and the tests pass, it seems that the current version of Tonic is OK with this version of Hyper.

**Comment by daviddrysdale** [comment]
> Does tonic work with this version of hyper?

Hmm, good point.  From a semver perspective, [`tonic 0.4.0`](https://crates.io/crates/tonic/0.4.0) depends on `hyper ^0.14.2` so `0.14.4` should be OK, but the CI actions that run on pull requests don't do anything serious with the `tink-testing` server (just a compile).

I'll trigger the [`crosstest` action](https://github.com/project-oak/tink-rust/actions?query=workflow%3Acrosstest) before merging to check that running the `tink-testing` server still works.

**Comment by daviddrysdale** [comment]
Added another commit to give an easier mechanism for manually running `crosstest`; result pending for this change[here](https://github.com/project-oak/tink-rust/runs/1861880004?check_suite_focus=true)

**Comment by daviddrysdale** [comment]
Added a couple more commits (and got a green `crosstest` run), PTAL.

**Comment by daviddrysdale** [comment]
(For some reason, running `cargo build --all-targets` at the top level gives a different result than `cargo build --manifest-path=testing/Cargo.toml` &hellip;)

**Review by conradgrobler — APPROVED** [review]

**Pull request merged**
