### PR TITLE
Bump transitive deps

### PR DESCRIPTION
**Pull request by daviddrysdale**

### CODE REVIEW

**Comment by daviddrysdale** [comment]
(will rebase on #433 later)

**Review by conradgrobler — APPROVED** [review]

**Comment by daviddrysdale** [comment]
PTAL -- I added one more commit (a RUSTSEC ignore) and actually bumped tink-core's rand dep this time.

**Comment by harryfei** [comment]
any plan for new version on crates.io ? Need this for my project.

**Comment by daviddrysdale** [comment]
I'll try to get a new release out soon (with the dependency updates and not much else, I think).

**Comment by harryfei** [comment]
@daviddrysdale Thank you.

**Pull request merged**
