### PR TITLE
Reorganize crate structure for tests to avoid circular dev-dependencies

### PR DESCRIPTION
**Pull request by daviddrysdale**
All intended to make it easier to publish the Tink crates to crates.io (#32).  Reorganize things so to avoid cyclic `dev-dependencies` between crates (as https://github.com/rust-lang/cargo/issues/4242 is not solved).
 - Rename `tink-testutil` to `tink-tests`, and &hellip;
 - Move all the integration tests into the `tink-tests` crate.
     -  Roughly: `git mv <crate>/tests tests/tests/<crate>_test` and add a `tests/tests/<crate>_test/mod.rs` file
 -  Also move the `testdata/` directory into the `tink-tests` crate.

This means that none of the core crates have any `dev-dependencies`, which allows them to be published. Publishing has to respect dependency order:
 - `tink-proto`
 - `tink`
 - `tink-prf`
    - also `tink-daead`, `tink-signature`, `tink-awskms`, `tink-gcpkms` can occur from here onwards
 - `tink-mac`
 - `tink-aead`, `tink-streaming-aead`
 - `rinkey` (depends on everything)

Also included in this PR:
 - Add initial packaging/versioning scripts

### CODE REVIEW

**Comment by daviddrysdale** [comment]
@tiziano88 :  no need to look at the code changes, but I wondered if you know any other way around the cyclic `dev-dependencies` problem described in the PR &ndash; it seems like any multi-crate repo with significant test coverage is likely to hit something similar.

**Comment by tiziano88** [comment]
I don't know of any decent solution of the top of my head, but I'll play around with it offline and let you know if I end up finding out anything useful.

Just so I understand: after your refactoring removing dev-deps , are things fine? Or does it still not work? Are you just trying to find an alternative solution?

**Comment by daviddrysdale** [comment]
I *think* the crates will be publishable (in a specific order) after removing `dev-dependencies`, but I'm not completely sure &ndash; I can't check by running `cargo package` because the later crates fail to find the earlier crates at crates.io.

So I guess we'll find out on first attempt to release&hellip;

**Review by conradgrobler — APPROVED** [review]

**Comment by daviddrysdale** [comment]
@tiziano88 any more thoughts on whether there's a better/easier way to do this?

**Comment by tiziano88** [comment]
> @tiziano88 any more thoughts on whether there's a better/easier way to do this?

Nothing in particular, sorry. The only thing I would have done differently is to try and use features instead of splitting crates, but that's a personal preference, and I'm not even sure it helps much in the end, so I think you should go ahead and see how it goes with the current structure.

**Review by tiziano88 — APPROVED** [review]

**Pull request merged**
